# ==========================================
# CONFIGURATION D'ÉVALUATION
# ==========================================
evaluation:
  output_dir: "results/uncertainty_residual_normalised_nll"
  model_name: "GradualExpansionUNet_res1"
  
  # Chemins vers les poids des modèles
  weights_path_reconstruction: "/home/ids/jfguerrero/Multimodal-change-detection-for-remote-sensing-images/checkpoints/filtered_clean_normalised/gradualexpansionunet_res_real_aug_SAM-0.5_MSE-0.0_MAE-1.0_lr-0.0002_no_mlp_residual_filtered_clean_normalised/best_model.pth"
  weights_path_uncertainty: "/home/ids/jfguerrero/Multimodal-change-detection-for-remote-sensing-images/checkpoints/uncertainty_dualbranchnafnet_run_normalised/dualbranchnafnet_ch64_laplace_nll_lr-0.0003_UNCERTAINTY/best_model.pth"
  weights_path_contrastive: "/home/ids/jfguerrero/Multimodal-change-detection-for-remote-sensing-images/checkpoints/contrastive_siamese_msi_hsi3/siamese_heterogene_lr5e-05_20260918_190158_a100_run/best_model.pth"
  use_amp: true
  log_to_wandb: false

# Configuration du modèle de reconstruction
model:
  name: "gradualexpansionunet_res"
  base_channel: 64
  interpolation_mode: "Bilinear"
  activation: "silu"
  with_batch_norm: true
  with_mlp_spectral: false
  final_activation: null

#modele contrastive
model_contrastive:
  name: "siamese_heterogene"
  base_channels: 32               # Note : 'base_channels' (pluriel) attendu par le script
  latent_dim: 64                  # Dimension de l'espace latent partagé
  load_model: null   

# Configuration du modèle d'incertitude (utilisé uniquement en mode uncertainty)
model_uncertainty:
  name: "dualbranchnafnet"
  base_channel: 64
  out_channels: 31
  middle_blk_num: 1
  enc_blk_nums: []
  dec_blk_nums: []
  drop_out_rate: 0.0
  final_activation: "softplus"

# Configuration des données
data:
  task: "spectral"
  simulated: false
  n_msi: 12                      # Nombre de canaux MSI (entrée)
  n_hsi: 195                      # Nombre de canaux HSI (sortie)
  batch_size: 8
  num_workers: 4
  augment: false                  # Désactivé pour l'évaluation
  augment_illumination: false     # Désactivé pour l'évaluation
  is_normalised: true
  is_residual: true
  
  # Chemins des jeux de données
  
  data_dir_train: "/home/ids/jfguerrero/Multimodal-change-detection-for-remote-sensing-images/data/patches_caches/train_contrastive1/train-clean"
  data_dir_val: "/home/ids/jfguerrero/Multimodal-change-detection-for-remote-sensing-images/data/patches_caches/val_contrastive1/val-clean"
  data_dir_test: "/home/ids/jfguerrero/Multimodal-change-detection-for-remote-sensing-images/data/patches_caches/test_contrastive1/test-clean"
wavelength_filtering:
  enabled: true
  # Liste des fenêtres atmosphériques (en nm) à retirer
  excluded_windows:
    - [1350, 1500]
    - [1800, 2000]
  excluded_bands: []
