# =====================================================================
# Configuration - Détection de Changement (Reconstruction & Incertitude)
# =====================================================================
# =====================================================================
# Configuration - Détection de Changement MSI/HSI (MuMuCD)
# =====================================================================

data:
  dataset_name: "mumucd"
  data_dir: "data/mumucd"
  n_msi: 12
  n_hsi: 195
  patch_size: 256
  scenes:
    - aranjuez
    - arborea
    - athens
    - baltijsk
    - bari
    - beer_sheva
    - beheira
    - beirut
    - belgrade
    - binh_dai
    - brasilia
    - camerino
    - cape_town
    - codigoro
    - copenhagen
    - copperton
  

model:
  base_channel: 64

model_uncertainty:
  base_channel: 64

evaluation:
  # Chemins vers les fichiers de poids des deux modèles nécessaires
  weights_path_reconstruction: "/home/ids/jfguerrero/Multimodal-change-detection-for-remote-sensing-images/checkpoints/filtered_clean_normalised2/gradualexpansionunet_res_real_aug_SAM-0.5_MSE-0.0_MAE-1.0_lr-0.0002_no_mlp_residual_filtered_clean_normalised/best_model.pth"
  weights_path_uncertainty: "/home/ids/jfguerrero/Multimodal-change-detection-for-remote-sensing-images/checkpoints/uncertainty_dualbranchnafnet_run_normalised/dualbranchnafnet_ch64_laplace_nll_lr-0.0003_UNCERTAINTY/best_model.pth"