experiment:
  name: "spectral_gradual_expansion_run"
  seed: 42
  project: "Multimodal-change-detection"
  entity: "JfGuerrero"
  output_dir: "checkpoints"

model:
  name: "gradualexpansionunet_res" # choices: ["unet", "gradualexpansionunet", "gradualexpansionunet_res"]
  activation: "silu"               # choices: ["relu", "leakyrelu", "silu"]
  interpolation_mode: "Bilinear"   # choices: ["Bilinear", "ConvTranspose2d"]
  with_mlp_spectral: false
  load_model: null                 # chemin vers un .pth si reprise d'entraînement, sinon null

data:
  task: "spectral"
  simulated: false
  augment: false
  is_normalised: false
  keep_atm_wave: true
  is_residual: true                # true pour gradualexpansionunet_res (x_init, x_interp, y), false pour les autres
  batch_size: 8
  num_workers: 4

training:
  epochs: 100
  lr: 0.0001
  loss_type: "spectral_loss"
  lambda_sam: 0.1
  lambda_mse: 1.0
  lambda_mae: 0.0
  scale_train_loss: 100.0        # Multiplicateur appliqué uniquement pendant le train_one_epoch
  optimizer_name: "adamw"        # choices: ["adamw", "adam", "sgd"]
  weight_decay: 0.0001           # si sgd ou adamw        
  warm_up: false                 # Active le LinearLR sur 3 époques si true
