# ==========================================
# CONFIGURATION D'ÉVALUATION
# ==========================================
evaluation:
  output_dir: "results/evaluation_report_real_unet_residual_clean_allwave"
  model_name: "gradualexpansionunet_res"
  weights_path_reconstruction: "/home/ids/jfguerrero/Multimodal-change-detection-for-remote-sensing-images/checkpoints/all_wave_clean/gradualexpansionunet_res_real_aug_SAM-0.5_MSE-0.0_MAE-1.0_lr-0.0002_no_mlp_residual/best_model.pth"
  weight_path_uncertainty: ""
# Configuration de l'architecture du modèle
model:
  name: "gradualexpansionunet_res"
  base_channel: 64
  interpolation_mode: "Bilinear"
  activation: "silu"
  with_batch_norm: true
  with_mlp_spectral: false
  final_activation: null

# Configuration des données
data:
  task: "spectral"
  simulated: false
  n_msi: 12                       # Nombre de canaux MSI (entrée)
  n_hsi: 195                       # Nombre de canaux HSI (sortie/vérité terrain)
  batch_size: 8
  num_workers: 0
  augment: false                  # Désactivé pour l'évaluation
  augment_illumination: false     # Désactivé pour l'évaluation
  is_normalised: false
  is_residual: true             # Mettre true si ton modèle utilise des résidus
  
  # Chemins des dossiers de données
  data_dir_train: "data/patches_caches/train-clean" # Requis par la fonction du dataloader
  data_dir_val: "data/patches_caches/val-clean"     # Requis par la fonction du dataloader
  data_dir_test: "data/patches_caches/test-clean"   # Dossier principal utilisé pour l'évaluation

wavelength_filtering:
  enabled: false
  # Liste des fenêtres atmosphériques (en nm) à retirer
  excluded_windows:
    - [1350, 1500]
    - [1800, 2000]
  excluded_bands: []